### ISSUE TITLE
ROMUN 2019 系统正式发布前调整

### ISSUE THREAD

**Issue by xujiazhao** [EasyMUN/DoveHouse#2]
**委员会信息调整如下：**
第一组：
- 英文：Joint Crisis Committees System
- 中文：危机联动系统
- 议题：危机联动——全球地缘政治体系综合模拟
- 背景图片：https://farm4.staticflickr.com/3338/3341815497_7cc8021631_b.jpg

第二组：
- 英文：China System
- 中文：中国系统
- 议题：消除贫困2020——脱贫攻坚，决胜全面小康
- 背景图片：https://bowenpress.com/wp-content/uploads/2017/03/MAIN201503051554076443833888346.jpg

第三组：
- 英文：留空
- 中文：1791 年法兰西革命体系——传奇再现
- 议题：法国社会的内外局势
- 背景图片：https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Valmy_Battle_painting.jpg/1280px-Valmy_Battle_painting.jpg

第四组：
- 英文：留空
- 中文：1979 英国下议院：不满冬天的阴霾
- 议题：二十世纪七十年代英国国内和国际局势问题的解决
1. 议题A：北爱尔兰独立与苏格兰权利下放问题
2. 议题B：国内工人罢工问题
3. 议题C：战后共识问题
- 背景图片：https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/House_of_Commons_Chamber_1.png/1280px-House_of_Commons_Chamber_1.png?1552132052695

第五组：
- 英文：留空
- 中文：1577 萬曆中興
- 议题：明中后期政治经济局势
- 背景图片：http://5b0988e595225.cdn.sohucs.com/images/20170926/933fdad43d0c40199a57386a96e0ee4e.jpeg

第六组：
- 英文：留空
- 中文：美国联邦最高法院
- 议题：杰作蛋糕店诉科罗拉多州民权委员会案
- 背景图片：http://5b0988e595225.cdn.sohucs.com/images/20180607/a78788f0ec56424389e25265f083f29d.jpeg

第七组：
- 英文：留空
- 中文：English Joint Committees (EJCS)
- 议题：Rwanda Holocaust
1. Committee A: Historical Office of High Commission for Human Right
2. Committee B: Historical United Nations Security Council
- 背景图片：https://www.worldvision.org/wp-content/uploads/2017/06/V324-81_19_29073_380531.jpg

**系统图片调整：**
请修改登陆界面图片为下方图片：
https://images.unsplash.com/photo-1454779132693-e5cd0a216ed3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1951&q=80

可否将侧边栏ROMUN logo尺寸缩小至其他icon尺寸
可否将默认头像修改为灰色用户icon，例如material design自带的icon中的一个

可否设置由我编辑“近期公告”内容

**报名支援选项调整**
请将报名志愿选项调整为上方委员会内容。

**Comment by CircuitCoder** [comment]
Done
